/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import crypto.KeyLoader;
import crypto.LicenseService;
import crypto.LicenseValidator;
import crypto.PublicKeyLoader;
import db.LicenseDAO;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import util.LicenseDateUtil;
import util.LicenseExporter;

/**
 *
 * @author Maxwell
 */
public class GeradorLicencaUI extends javax.swing.JFrame {
    
    /**
     * Creates new form GeradorLicencaUI
     */
    public GeradorLicencaUI() {
        initComponents();
        //Imagem do software
        ImageIcon iconUCKG = new ImageIcon(this.getClass().getClassLoader().getResource("img/UltraCipaKEY.png"));
        this.setIconImage(iconUCKG .getImage());
        
        txtHWID.setText(util.HWID.get());
        txtHWID.setEditable(true);
        
    }//Construtor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHWID = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnExportarLicenca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLicense = new javax.swing.JTextArea();
        btnGerarLicenca = new javax.swing.JButton();
        cmbLicenseType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblAvisoHWID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGerarLicenca1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UltraCIPA Key Generator");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setMaximumSize(new java.awt.Dimension(900, 600));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(900, 600));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("E-MAIL *");
        panelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("LICENÇA");
        panelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TIPO *");
        panelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 70, 30));

        txtHWID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelPrincipal.add(txtHWID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 630, 35));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHWID(evt);
            }
        });
        panelPrincipal.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 480, 35));

        btnExportarLicenca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnExportarLicenca.setText("EXPORTAR LICENÇA");
        btnExportarLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarLicencaActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnExportarLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 220, 35));

        txtLicense.setColumns(20);
        txtLicense.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtLicense.setLineWrap(true);
        txtLicense.setRows(5);
        txtLicense.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtLicense);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 790, 100));

        btnGerarLicenca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnGerarLicenca.setText("GERAR LICENÇA");
        btnGerarLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarLicencaActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnGerarLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 190, 35));

        cmbLicenseType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbLicenseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "TRIAL", "MONTHLY", "ANNUAL", "LIFETIME" }));
        panelPrincipal.add(cmbLicenseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 150, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("HWID");
        panelPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        lblAvisoHWID.setText("VERIFICAR SE O HWID ACIMA JÁ ESTÁ REGISTRADO EM NOME ALGUM CLIENTE.");
        panelPrincipal.add(lblAvisoHWID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 630, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 176, 80));
        jLabel1.setText("UltraCIPA Key Generator");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 280, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UltraCipaKEY.png"))); // NOI18N
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btnGerarLicenca1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnGerarLicenca1.setText("LIMPAR");
        btnGerarLicenca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarLicenca1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnGerarLicenca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 190, 35));

        getContentPane().add(panelPrincipal);

        setSize(new java.awt.Dimension(918, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarLicencaActionPerformed
        try {

            String email = txtEmail.getText();
            String hwid = txtHWID.getText();
            int tipo = cmbLicenseType.getSelectedIndex();

            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(null, "DIGITE O E-MAIL.");
                txtEmail.requestFocus();
                return;
            }

            if (hwid.isEmpty()) {
                JOptionPane.showMessageDialog(null, "DIGITE O HWID.");
                txtHWID.requestFocus();
                return;
            }

            if (tipo == 0) {
                JOptionPane.showMessageDialog(null, "SELECIONE O TIPO DE LICENÇA.");
                cmbLicenseType.requestFocus();
                return;
            }

            // 🧾 tipo de licença (pode vir de ComboBox depois)
            String type = cmbLicenseType.getSelectedItem().toString();

            // ⏳ cálculo da expiração
            String expires;

            switch (type) {
                case "TRIAL":
                    expires = LicenseDateUtil.addDays(7);
                    break;
                case "MONTHLY":
                    expires = LicenseDateUtil.addMonths(1);
                    break;
                case "ANNUAL":
                    expires = LicenseDateUtil.addYears(1);
                    break;
                case "LIFETIME":
                    expires = "2099-12-31";
                    break;
                default:
                    expires = LicenseDateUtil.addYears(1);
            }

            // 📦 payload completo
            String payload = "{"
                    + "\"email\":\"" + email + "\","
                    + "\"hwid\":\"" + hwid + "\","
                    + "\"type\":\"" + type + "\","
                    + "\"expires\":\"" + expires + "\""
                    + "}";

            // 🔐 RSA
            PrivateKey privateKey = KeyLoader.loadPrivateKey();
            String license = LicenseService.generate(payload, privateKey);

            // 📺 UI
            txtLicense.setText(license);

            // 💾 banco
            LicenseDAO.save(email, hwid, license, type, expires);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO TENTAR GERAR A LICENÇA: " + e);
        }
    }//GEN-LAST:event_btnGerarLicencaActionPerformed

    private void btnExportarLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarLicencaActionPerformed
        try {
            String license = txtLicense.getText().trim();

            if (license.isEmpty()) {
                JOptionPane.showMessageDialog(null, "O CAMPO LICENÇA ESTÁ VAZIO.\nGERE  UMA LICENÇA PRIMEIRO.");
                return;
            }

            JFileChooser chooser = new JFileChooser();

            chooser.setSelectedFile(new File("licenseUltraCIPA.dat"));

            if (chooser.showSaveDialog(this)
                    == JFileChooser.APPROVE_OPTION) {

                File file = chooser.getSelectedFile();

                LicenseExporter.export(file, license);

                JOptionPane.showMessageDialog(null, "LICENÇA EXPORTADA COM SUCESSO.");
            }
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(null, "ERRO AO TENTAR EXPORTA A LICENÇA: " + e);
        } catch (Exception ex) {
            Logger.getLogger(GeradorLicencaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExportarLicencaActionPerformed

    private void txtHWID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHWID
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            cmbLicenseType.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtHWID

    private void btnGerarLicenca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarLicenca1ActionPerformed
        //apenas para testes
        PublicKey pk = null;
        try {
            pk = PublicKeyLoader.load();
        } catch (Exception ex) {
            Logger.getLogger(GeradorLicencaUI.class.getName()).log(Level.SEVERE, null, ex);
        }

boolean valid = LicenseValidator.verify(txtLicense.getText(), pk);

if (valid) {
    JOptionPane.showMessageDialog(null, "LICENÇA VÁLIDA.");
} else {
    JOptionPane.showMessageDialog(null, "LICENÇA INVÁLIDA.");
}
    }//GEN-LAST:event_btnGerarLicenca1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeradorLicencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeradorLicencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeradorLicencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeradorLicencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeradorLicencaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarLicenca;
    private javax.swing.JButton btnGerarLicenca;
    private javax.swing.JButton btnGerarLicenca1;
    public javax.swing.JComboBox<String> cmbLicenseType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvisoHWID;
    private javax.swing.JPanel panelPrincipal;
    public javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHWID;
    private javax.swing.JTextArea txtLicense;
    // End of variables declaration//GEN-END:variables
}
